title: Chris Finazzo
email: chris@chrisfinazzo.com
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     [_headers, _redirects]
exclude:     []
keep_files:  ['.git','.svn']
timezone:    America/New_York
encoding:    utf-8
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

future:      false
show_drafts: false
limit_posts: 0
highlighter: rouge
feed:
  path: rss.xml

permalink:   /:year/:month/:day/:title/

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
 links:
   output: true

markdown:      kramdown
markdown_ext:  markdown,md

excerpt_separator: ""

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     ""
url:         https://chrisfinazzo.com
lsi:         false

github:
    url: https://github.com/chrisfinazzo
linkedin:
    url: https://linkedin.com/in/chrisfinazzo
twitter:
    url: https://twitter.com/chrisfinazzo
