title: Chris Finazzo
email: chris@chrisfinazzo.com
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     []
exclude:     ['.jekyll-cache']
keep_files:  ['.git','.svn']
timezone:    America/New_York
encoding:    utf-8
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/footnotes
  - jekyll-commonmark
#   - jekyll-webmention_io

future:      false
show_drafts: false
limit_posts: 0
highlighter: rouge
feed:
  path: rss.xml
  path: notes-rss.xml

permalink:   /:year/:month/:day/:title/

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

webmentions:
  syndication:
    mastodon:
      endpoint: https://brid.gy/publish/mastodon
    twitter:
      endpoint: https://brid.gy/publish/twitter

collections:
  notes:
    output: true
    permalink: /notes/:year/:month/:day/:title/
  links:
    output: true
    permalink: /links/:year/:month/:day/:title/
defaults:
-
  scope:
    path: ""
    type: "notes"
  values:
    layout: "note"
    title: ""
    permalink: "/:collection/:title/"
    post_type: "Note"

markdown: CommonMark
commonmark:
  options: ["UNSAFE"]
  extensions: ["strikethrough", "table"]
markdown_ext:  markdown,md

excerpt_separator: ""

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     ""
url:         https://chrisfinazzo.com
lsi:         false

github:
    url: https://github.com/chrisfinazzo
linkedin:
    url: https://linkedin.com/in/chrisfinazzo
mastodon:
    url: https://mastodon.social/@chrisfinazzo
twitter:
    url: https://twitter.com/chrisfinazzo
