#!/bin/bash

set -e # Stop the script if there's an error

git push origin master && rsync -crz --exclude-from='rsync-exclude.txt' --delete _site/ cfinazzo1@micro.chrisfinazzo.com:/home/cfinazzo1/micro.chrisfinazzo.com
