# WWW
[[redirects]]
from = "/www.chrisfinazzo.com"
to = "/chrisfinazzo.com"
status = 301
force = false
# Netlify
[[redirects]]
from = "https://relaxed-meninsky-6eca95.netlify.com/*"
to = "https://chrisfinazzo.com/"
status = 301
force = false
# 404
[[redirects]]
    from = "*"
    to = "/404"
    status = 404

[[headers]]
  for = "/*"

  [headers.values]  
    Cache-Control = "no-transform"
    Content-Security-Policy-Report-Only = '''
    style-src 'self';
    default-src 'self';
    object-src 'none';
    img-src https:;
    script-src 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=';
    'unsafe-inline';
    frame-ancestors 'none';
    report-uri https://chrisfinazzo.report-uri.com/'''
    Upgrade-Insecure-Requests = "1"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
