# WWW
[[redirects]]
from = "/www.chrisfinazzo.com"
to = "/chrisfinazzo.com"
status = 301
force = false
# Netlify
[[redirects]]
from = "https://relaxed-meninsky-6eca95.netlify.com/*"
to = "https://chrisfinazzo.com/"
status = 301
force = false
# 404
[[redirects]]
from = "*"
to = "/404"
status = 404

[[plugins]]
  package = "netlify-plugin-webmentions"
  
  [plugins.inputs]
    baseUrl = "https://chrisfinazzo.com"
    feedPath = "/notes-rss.xml"
    limit = 1

[[headers]]
  for = "/*"

  [headers.values]  
    Cache-Control = "no-transform"
    Permissions-Policy = "interest-cohort=()"
#     Content-Security-Policy = '''
#     default-src 'none';
#     script-src 'self';
#     style-src 'self';
#     base-uri 'self';
#     object-src 'none';
#     connect-src 'self';
#     font-src 'self';
#     frame-src https://giphy.com;
#     img-src https: 'self' https://imgs.xkcd.com;
#     manifest-src 'self';
#     media-src 'self';
#     worker-src 'self'; '''
    Upgrade-Insecure-Requests = "1"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
