[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"
        Upgrade-Insecure-Requests = "1"
        Cache-Control = "no-transform"
# [[redirects]]
# from = "/www.chrisfinazzo.com"
# to = "/chrisfinazzo.com"
# status = 301
# force = false
[[redirects]]
from = "https://relaxed-meninsky-6eca95.netlify.com/*"
to = "https://chrisfinazzo.com/"
status = 301
force = false
