# WWW
[[redirects]]
from = "/www.chrisfinazzo.com"
to = "/chrisfinazzo.com"
status = 301
force = false
# Netlify
[[redirects]]
from = "https://relaxed-meninsky-6eca95.netlify.com/*"
to = "https://chrisfinazzo.com/"
status = 301
force = false
# 404
[[redirects]]
from = "*"
to = "/404"
status = 404

[[headers]]
  for = "/*"

  [headers.values]  
    Cache-Control = "no-transform"
    Content-Security-Policy-Report-Only = '''
    default-src 'self';
    script-src 'self';
    style-src 'self';
    base-uri 'self';
    object-src 'none';
    connect-src 'self';
    font-src 'self';
    form-action https://formspree.io/chris@chrisfinazzo.com;
    frame-src 'self' https://giphy.com;
    img-src https:;
    manifest-src 'self';
    media-src 'self';
    worker-src 'self';
    report-uri https://5e8f35ad38707b8edb26c977.endpoint.csper.io; '''
    Upgrade-Insecure-Requests = "1"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
